// Top-level build file where you can add configuration options common to all sub-projects/modules.

ext {
    compileSdkVersion = 36
    minSdkVersion = 28
    targetSdkVersion = 36
    javaVersion = JavaVersion.VERSION_17
    kotlin_version = '2.3.21'
}

buildscript {
    repositories {
        mavenCentral()
        google()
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.3.21"
        classpath 'org.jlleitschuh.gradle:ktlint-gradle:14.2.0'
        classpath "dev.detekt:detekt-gradle-plugin:2.0.0-alpha.3"
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
}

tasks.register("clean", Delete) {
    delete(rootProject.layout.buildDirectory)
}
